import type { Metadata } from "next";
import "./globals.css";
import { poppins } from "@/utils/fonts";
import { Toaster } from "sonner";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins}`}
      >
        {children}
        <Toaster
          position="top-center"
          theme="light"
          duration={5000}
        />
      </body>
    </html>
  );
}
